name: zinny
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask
  - jinja2
  - numpy
  - pandas
  # pip dependencies
  - pip
  - pip:
      - zinny-surveys
      - zinny-api
