name: zinny
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask
  - jinja2
  - numpy
  - pandas
  # pip dependencies
  - pip
  - pip:
      - git+https://github.com/RyLaney/zinny-surveys.git
      - git+https://github.com/RyLaney/zinny-api.git
